package greencity.enums;

public enum NotificationType {
    LIKED_NEWS, COMMENTED_NEWS,
    LIKED_EVENT, COMMENTED_EVENT,LIKED_EVENT_COMMENT, REPLIED_EVENT_COMMENT,
    UPDATED_EVENT, CANCELED_EVENT,
    LIKED_HABIT, COMMENTED_HABIT,
    LIKED_NEWS_COMMENT, REPLIED_NEWS_COMMENT,
    TAGGED_USER_UNDER_NEWS, TAGGED_USER_UNDER_EVENT
}
