package greencity.enums;

public enum NotificationType {
    LIKED_NEWS, COMMENTED_NEWS,
    LIKED_EVENT, COMMENTED_EVENT,
    LIKED_HABIT, COMMENTED_HABIT, CANCELED_HABIT, UPDATED_HABIT,
    LIKED_COMMENT, REPLIED_COMMENT
}
